name = "gijinka-manga-bot"
compatibility_date = "2023-12-01"
main = "src/server.ts"

[vars]
DISCORD_PUBLIC_KEY = "de20f3250cde0d4e3613c0c7d78f1f7ad2d57adb3050d0ec309a571d5f92368d"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
